
spring:
  profiles:
    active: test

server:
  port: 8166


mybatis:
  mapper-locations: classpath:/mapper/*.xml
---
spring.profiles: test

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/sm2_update?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  druid:
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 1
    host: localhost
    port: 6379
myProps:
  serviceIp: 127.0.0.1
  userDB: sm2_user_test
  contentDB: sm2_content_test
---
spring.profiles: aliTest

spring:
  datasource:
    name: test
    url: jdbc:mysql://rdsnnefjyzvy2eq.mysql.rds.aliyuncs.com:3306/sm2_content_test?characterEncoding=utf8&useSSL=false
    username: sma
    password: smadb123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  druid:
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 1
    host: localhost
    port: 6379
    password: sider##sm2-bcl

myProps:
  serviceIp: 114.215.128.198
  userDB: sm2_user_test
  contentDB: sm2_content_test


---
spring.profiles: aliPro

spring:
  datasource:
    name: test
    url: jdbc:mysql://rdsnnefjyzvy2eq.mysql.rds.aliyuncs.com:3306/sm2_content?characterEncoding=utf8&useSSL=false
    username: sma
    password: smadb123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  druid:
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 1
    host: localhost
    port: 6379
#    password: sider##sm2-bcl
myProps:
  serviceIp: 121.42.154.243
  userDB: sm2_user
  contentDB: sm2_content






